[build-system]
requires = ["setuptools>=58.0.4", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pylint]
    [tool.pylint.'MESSAGES CONTROL']
        disable = [
            "logging-fstring-interpolation",
            "too-many-arguments",
            "too-many-branches",
            "too-many-instance-attributes",
            "too-many-locals",
            "too-many-nested-blocks",
            "too-many-statements",
        ]